### PR TITLE
Support DEL command in scan_reader

### PR DESCRIPTION
**Pull request by xhs**
Partially fix issue #818

### CODE REVIEW

**Comment by chendexiaqu** [comment]
> Partially fix issue #818

what do you mean by partially?

**Comment by chendexiaqu** [comment]
@xhs do we have a specific time for a new release version that contains this fix?

**Comment by suxb201** [comment]
@chendexiaqu I just released the new version: https://github.com/tair-opensource/RedisShake/releases/tag/v4.1.1

**Comment by chendexiaqu** [comment]
@suxb201 Aliyun employee? Can I add you on Ali Ding. I'm "剑沉". I have some questions about redis-shake on basic redis  migration theory

**Pull request merged**
